version: "3"
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  backend:
    build:
      context: ./be
    ports:
      - "8080:8080"
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
    volumes:
      - ./be:/usr/src/app
  frontend:
    build:
      context: ./fe
    ports:
      - "3000:3000"
    volumes:
      - ./fe:/usr/src/app
